In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
y2015['loan_status'].head(50)

0         Current
1         Current
2      Fully Paid
3         Current
4      Fully Paid
5         Current
6         Current
7      Fully Paid
8         Current
9      Fully Paid
10        Current
11        Current
12        Current
13        Current
14     Fully Paid
15        Current
16        Current
17        Current
18        Current
19        Current
20        Current
21     Fully Paid
22        Current
23        Current
24        Current
25        Current
26        Current
27     Fully Paid
28        Current
29        Current
30     Fully Paid
31        Current
32        Current
33    Charged Off
34        Current
35        Current
36        Current
37     Fully Paid
38        Current
39        Current
40        Current
41        Current
42        Current
43        Current
44     Fully Paid
45        Current
46        Current
47        Current
48        Current
49        Current
Name: loan_status, dtype: object

In [9]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

In [10]:
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015.int_rate.str.strip('%'), errors='coerce')

y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [11]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,60 months,15.99,316.07,D,5 years,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,60 months,19.99,317.86,E,1 year,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,36 months,11.99,664.20,B,10+ years,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
y2015 = y2015[:-2]

In [13]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421090,36371250.0,39102635.0,10000.0,10000.0,10000.0,36 months,11.99,332.10,B,8 years,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421091,36441262.0,39152692.0,24000.0,24000.0,24000.0,36 months,11.99,797.03,B,10+ years,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,60 months,15.99,316.07,D,5 years,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,60 months,19.99,317.86,E,1 year,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,36 months,11.99,664.20,B,10+ years,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0

In [14]:
pd.get_dummies(y2015)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,...,0,0,0,0,0,1,0,0,0,0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,...,0,0,0,0,0,1,0,0,0,0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,...,0,0,0,0,0,1,0,0,0,0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,...,0,0,0,0,0,1,0,0,0,0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,...,0,0,0,0,0,1,0,0,0,0
5,68506798.0,73396623.0,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,...,0,0,0,0,0,1,0,0,0,0
6,68566886.0,73456723.0,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,...,0,0,0,0,0,1,0,0,0,0
7,68577849.0,73467703.0,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,...,0,0,0,0,0,1,0,0,0,0
8,66310712.0,71035433.0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,...,0,0,0,0,0,1,0,0,0,0
9,68476807.0,73366655.0,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,...,0,0,0,0,0,1,0,0,0,0
10,68341763.0,72928789.0,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,...,0,0,0,0,0,0,1,1,0,0
11,68356421.0,73246236.0,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,...,0,0,0,0,0,1,0,0,0,0
12,68426545.0,73316365.0,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,...,0,0,0,0,0,1,0,0,0,0
13,68407277.0,73297111.0,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,...,0,0,0,0,0,1,0,0,0,0
14,68355089.0,73244858.0,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,...,0,0,0,0,0,1,0,0,0,0
15,68466926.0,73356763.0,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,...,0,0,0,0,0,1,0,0,0,0
16,68338832.0,73542831.0,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,...,0,0,0,0,0,1,0,0,0,0
17,68426831.0,73316657.0,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,...,0,0,0,0,0,1,0,0,0,0
18,66624733.0,71350547.0,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,...,0,0,0,0,0,1,0,0,0,0
19,68616873.0,73519699.0,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,...,0,0,0,0,0,1,0,0,0,0
20,67275481.0,72077199.0,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,...,0,0,0,0,0,1,0,0,0,0
21,68476668.0,73366513.0,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,...,1,0,0,0,0,1,0,0,0,0
22,68476702.0,73366548.0,28000.0,28000.0,28000.0,13.44,949.38,125000.0,7.49,0.0,...,0,0,0,0,0,1,0,0,0,0
23,68436666.0,73326493.0,5000.0,5000.0,5000.0,13.44,169.54,79000.0,12.70,0.0,...,0,0,0,0,0,1,0,0,0,0
24,68596180.0,73485987.0,20000.0,20000.0,20000.0,5.32,602.30,65000.0,18.83,0.0,...,0,0,0,0,0,1,0,0,0,0
25,67849662.0,72708407.0,4225.0,4225.0,4225.0,14.85,146.16,35000.0,15.22,2.0,...,0,0,0,0,0,1,0,0,0,0
26,68526883.0,73416719.0,15000.0,15000.0,15000.0,5.32,451.73,44000.0,15.34,0.0,...,0,0,0,0,0,1,0,0,0,0
27,68607141.0,73509983.0,17600.0,17600.0,17600.0,5.32,530.03,88000.0,26.59,0.0,...,1,0,0,0,0,1,0,0,0,0
28,68476715.0,73366561.0,6000.0,6000.0,6000.0,7.49,186.61,100000.0,13.28,1.0,...,0,0,0,0,0,1,0,0,0,0
29,67715283.0,72569997.0,16000.0,16000.0,16000.0,12.88,538.18,65000.0,18.96,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,36631385.0,39374138.0,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,...,0,0,0,0,0,1,0,0,0,0
421066,36231083.0,38942474.0,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,...,0,0,0,0,0,1,0,0,0,0
421067,36691397.0,39434133.0,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,...,0,0,0,0,0,1,0,0,0,0
421068,36743377.0,39486112.0,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,...,0,0,0,0,0,1,0,0,0,0
421069,36331554.0,39042967.0,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,...,0,0,0,0,0,1,0,0,0,0
421070,36460697.0,39182359.0,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,...,0,0,0,0,0,1,0,0,0,0
421071,35773415.0,38468842.0,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,...,0,0,0,0,0,1,0,0,0,0
421072,36250801.0,38962184.0,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,...,0,0,0,0,0,1,0,0,0,0
421073,36371802.0,39103231.0,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,...,0,0,0,0,0,1,0,0,0,0
421074,36440728.0,39152101.0,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,...,0,0,0,0,0,1,0,0,0,0
421075,36361815.0,39093260.0,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,...,0,0,0,0,0,1,0,0,0,0
421076,35591131.0,38288343.0,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,...,0,0,0,0,0,1,0,0,0,0
421077,36201871.0,38913321.0,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,...,0,0,0,0,0,1,0,0,0,0
421078,36381756.0,39013193.0,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,...,0,0,0,0,0,1,0,0,0,0
421079,36231724.0,38943173.0,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,...,0,0,1,0,0,1,0,0,0,0
421080,36301729.0,39023153.0,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,...,0,0,0,0,0,1,0,0,0,0
421081,36250208.0,38961532.0,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,...,0,0,0,0,0,1,0,0,0,0
421082,36241316.0,38952731.0,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,...,0,0,0,0,0,1,0,0,0,0
421083,36231718.0,38943165.0,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,...,0,0,0,0,0,1,0,0,0,0
421084,36381704.0,39013139.0,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,...,0,0,0,0,0,1,0,0,0,0
421085,36421485.0,39142898.0,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,...,0,0,1,0,0,1,0,0,0,0
421086,35094480.0,37777829.0,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,...,0,0,0,0,0,1,0,0,0,0
421087,36260758.0,38972123.0,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,...,0,0,1,0,0,1,0,0,0,0
421088,36221446.0,38932858.0,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,...,1,0,0,0,0,1,0,0,0,0
421089,36330911.0,39042282.0,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,...,0,0,0,0,0,1,0,0,0,0
421090,36371250.0,39102635.0,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,...,0,0,0,0,0,1,0,0,0,0
421091,36441262.0,39152692.0,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,...,0,0,0,0,0,1,0,0,0,0
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,...,0,0,0,0,0,1,0,0,0,0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,...,0,0,1,0,0,1,0,0,0,0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,...,0,0,0,0,0,1,0,0,0,0

In [15]:
y2015.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,60 months,14.85,379.39,C,10+ years,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,36 months,7.49,298.58,A,8 years,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,36 months,7.49,777.55,A,10+ years,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,36 months,6.49,858.05,A,10+ years,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,36 months,19.89,320.99,E,8 years,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [16]:
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\dpierce\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98040892, 0.98017145, 0.9816675 , 0.98164375, 0.96722869,
       0.97905486, 0.86544444, 0.98040799, 0.97997958, 0.98005035])

In [18]:
from feature_selector import FeatureSelector

SyntaxError: invalid syntax (feature_selector.py, line 7)

In [19]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

In [56]:
X.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_tl_bal_gt_0,num_sats,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,term_ 36 months,term_ 60 months,grade_A,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G,emp_length_1 year,emp_length_10+ years,emp_length_2 years,emp_length_3 years,emp_length_4 years,emp_length_5 years,emp_length_6 years,emp_length_7 years,emp_length_8 years,emp_length_9 years,emp_length_< 1 year,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,issue_d_Apr-2015,issue_d_Aug-2015,issue_d_Dec-2015,issue_d_Feb-2015,issue_d_Jan-2015,issue_d_Jul-2015,issue_d_Jun-2015,issue_d_Mar-2015,issue_d_May-2015,issue_d_Nov-2015,issue_d_Oct-2015,issue_d_Sep-2015,pymnt_plan_n,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,title_Business,title_Car financing,title_Credit Card/Auto Repair,title_Credit card refinancing,title_Debt consolidation,title_DebtC,title_Green loan,title_Home buying,title_Home improvement,title_Learning and training,title_Major purchase,title_Medical expenses,title_Moving and relocation,title_New Baby and New House (CC Consolidate),title_Other,title_Pay off Lowes Card,title_Paying off higher interest cards & auto,title_Prescription Drug and Medical Costs,title_SAVE,title_Simple Loan Until Contract Is Completed,title_Student Loan,title_Trying to come back to reality!,title_Vacation,title_considerate,title_new day,title_new kitchen for momma!,title_odymeds,initial_list_status_f,initial_list_status_w,last_pymnt_d_Apr-2015,last_pymnt_d_Apr-2016,last_pymnt_d_Aug-2015,last_pymnt_d_Aug-2016,last_pymnt_d_Dec-2015,last_pymnt_d_Dec-2016,last_pymnt_d_Feb-2015,last_pymnt_d_Feb-2016,last_pymnt_d_Jan-2015,last_pymnt_d_Jan-2016,last_pymnt_d_Jan-2017,last_pymnt_d_Jul-2015,last_pymnt_d_Jul-2016,last_pymnt_d_Jun-2015,last_pymnt_d_Jun-2016,last_pymnt_d_Mar-2015,last_pymnt_d_Mar-2016,last_pymnt_d_May-2015,last_pymnt_d_May-2016,last_pymnt_d_Nov-2015,last_pymnt_d_Nov-2016,last_pymnt_d_Oct-2015,last_pymnt_d_Oct-2016,last_pymnt_d_Sep-2015,last_pymnt_d_Sep-2016,next_pymnt_d_Feb-2017,next_pymnt_d_Jan-2017,next_pymnt_d_Jul-2016,next_pymnt_d_Mar-2017,last_credit_pull_d_Apr-2015,last_credit_pull_d_Apr-2016,last_credit_pull_d_Aug-2015,last_credit_pull_d_Aug-2016,last_credit_pull_d_Dec-2014,last_credit_pull_d_Dec-2015,last_credit_pull_d_Dec-2016,last_credit_pull_d_Feb-2015,last_credit_pull_d_Feb-2016,last_credit_pull_d_Jan-2015,last_credit_pull_d_Jan-2016,last_credit_pull_d_Jan-2017,last_credit_pull_d_Jul-2015,last_credit_pull_d_Jul-2016,last_credit_pull_d_Jun-2015,last_credit_pull_d_Jun-2016,last_credit_pull_d_Mar-2015,last_credit_pull_d_Mar-2016,last_credit_pull_d_May-2015,last_credit_pull_d_May-2016,last_credit_pull_d_Nov-2015,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,0.0,11.0,2.0,19108.0,19.0,13668.88,13668.88,4519.68,4519.68,2331.12,2188.56,0.0,0.0,0.0,379.39,0.0,1.0,0.0,0.0,31329.0,284700.0,6.0,2848.0,0.0,0.0,294.0,11.0,6.0,2.0,2.0,6.0,9.0,6.0,8.0,6.0,9.0,9.0,11.0,0.0,0.0,2.0,78.9,0.0,2.0,298100.0,31329.0,281300.0,13400.0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,0.0,7.0,0.0,7722.0,9.0,6635.69,6635.69,3572.97,3572.97,2964.31,608.66,0.0,0.0,0.0,298.58,0.0,1.0,0.0,0.0,55387.0,13000.0,2.0,7912.0,0.0,0.0,91.0,9.0,9.0,0.0,0.0,3.0,3.0,3.0,3.0,5.0,4.0,3.0,7.0,0.0,0.0,2.0,100.0,0.0,0.0,88635.0,55387.0,12500.0,75635.0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,1.0,9.0,0.0,20862.0,19.0,0.00,0.00,26224.23,26224.23,25000.00,1224.23,0.0,0.0,0.0,20807.39,0.0,1.0,0.0,0.0,305781.0,38400.0,2.0,33976.0,0.0,0.0,168.0,13.0,13.0,3.0,0.0,3.0,3.0,5.0,6.0,7.0,5.0,3.0,9.0,0.0,0.0,0.0,100.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,0.0,16.0,0.0,51507.0,24.0,19263.77,19263.77,10271.36,10271.36,8736.23,1535.13,0.0,0.0,0.0,858.05,0.0,1.0,0.0,0.0,221110.0,79900.0,1.0,13819.0,0.0,0.0,379.0,19.0,19.0,2.0,0.0,7.0,9.0,9.0,11.0,4.0,13.0,9.0,16.0,0.0,0.0,0.0,91.7,0.0,0.0,304003.0,74920.0,41500.0,42503.0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,4.0,18.0,1.0,9568.0,19.0,0.00,0.00,9190.49,9190.49,8650.00,540.49,0.0,0.0,0.0,8251.42,0.0,1.0,0.0,0.0,18926.0,20750.0,17.0,1051.0,0.0,0.0,95.0,0.0,0.0,0.0,0.0,2.0,17.0,2.0,2.0,2.0,17.0,13.0,18.0,0.0,0.0,12.0,100.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [57]:
X_1 = sm.add_constant(X)
X_1 = X_1.astype(np.float64)
X_1.dtypes

id                                           float64
member_id                                    float64
loan_amnt                                    float64
funded_amnt                                  float64
funded_amnt_inv                              float64
int_rate                                     float64
installment                                  float64
annual_inc                                   float64
dti                                          float64
delinq_2yrs                                  float64
inq_last_6mths                               float64
open_acc                                     float64
pub_rec                                      float64
revol_bal                                    float64
total_acc                                    float64
out_prncp                                    float64
out_prncp_inv                                float64
total_pymnt                                  float64
total_pymnt_inv                              float64
total_rec_prncp                              float64
total_rec_int                                float64
total_rec_late_fee                           float64
recoveries                                   float64
collection_recovery_fee                      float64
last_pymnt_amnt                              float64
collections_12_mths_ex_med                   float64
policy_code                                  float64
acc_now_delinq                               float64
tot_coll_amt                                 float64
tot_cur_bal                                  float64
                                              ...
last_credit_pull_d_Apr-2016                  float64
last_credit_pull_d_Aug-2015                  float64
last_credit_pull_d_Aug-2016                  float64
last_credit_pull_d_Dec-2014                  float64
last_credit_pull_d_Dec-2015                  float64
last_credit_pull_d_Dec-2016                  float64
last_credit_pull_d_Feb-2015                  float64
last_credit_pull_d_Feb-2016                  float64
last_credit_pull_d_Jan-2015                  float64
last_credit_pull_d_Jan-2016                  float64
last_credit_pull_d_Jan-2017                  float64
last_credit_pull_d_Jul-2015                  float64
last_credit_pull_d_Jul-2016                  float64
last_credit_pull_d_Jun-2015                  float64
last_credit_pull_d_Jun-2016                  float64
last_credit_pull_d_Mar-2015                  float64
last_credit_pull_d_Mar-2016                  float64
last_credit_pull_d_May-2015                  float64
last_credit_pull_d_May-2016                  float64
last_credit_pull_d_Nov-2015                  float64
last_credit_pull_d_Nov-2016                  float64
last_credit_pull_d_Oct-2015                  float64
last_credit_pull_d_Oct-2016                  float64
last_credit_pull_d_Sep-2015                  float64
last_credit_pull_d_Sep-2016                  float64
application_type_INDIVIDUAL                  float64
application_type_JOINT                       float64
verification_status_joint_Not Verified       float64
verification_status_joint_Source Verified    float64
verification_status_joint_Verified           float64
Length: 201, dtype: object

In [90]:
#model = sm.OLS(Y, X_1).fit()
#model.pvalues

In [59]:
Y.unique()

array(['Current', 'Fully Paid', 'Charged Off', 'Late (31-120 days)',
       'In Grace Period', 'Default', 'Late (16-30 days)'], dtype=object)

In [60]:
from matplotlib.mlab import PCA as mlabPCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [61]:
sklearn_pca = PCA(n_components = 10)
Y_sklearn = sklearn_pca.fit_transform(X)

In [72]:
Y_sklearn
np.set_printoptions(suppress=True)
print(sklearn_pca.explained_variance_ratio_)

[0.99842296 0.00122397 0.00029577 0.00002437 0.00001545 0.00000953
 0.00000335 0.00000155 0.00000111 0.00000068]

In [77]:
Y_sklearn[1]

array([-21281614.85018383,   -150995.63064154,   -123768.77782625,
            5247.05685642,    -37426.38526333,    -19538.45980112,
           16023.39185774,      7369.95566233,     -2146.16005969,
             318.42429549])

In [78]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
np.random.seed(123)

In [79]:
label_encoder = LabelEncoder()

In [81]:
y_encoded = label_encoder.fit_transform(y2015['loan_status']).astype('float64')

In [88]:
y_e = pd.DataFrame()
y_e['outcome_encoded'] = y_encoded
y_e.head()

   outcome_encoded
0              1.0
1              1.0
2              3.0
3              1.0
4              3.0

In [85]:
X.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_tl_bal_gt_0,num_sats,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,term_ 36 months,term_ 60 months,grade_A,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G,emp_length_1 year,emp_length_10+ years,emp_length_2 years,emp_length_3 years,emp_length_4 years,emp_length_5 years,emp_length_6 years,emp_length_7 years,emp_length_8 years,emp_length_9 years,emp_length_< 1 year,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,issue_d_Apr-2015,issue_d_Aug-2015,issue_d_Dec-2015,issue_d_Feb-2015,issue_d_Jan-2015,issue_d_Jul-2015,issue_d_Jun-2015,issue_d_Mar-2015,issue_d_May-2015,issue_d_Nov-2015,issue_d_Oct-2015,issue_d_Sep-2015,pymnt_plan_n,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,title_Business,title_Car financing,title_Credit Card/Auto Repair,title_Credit card refinancing,title_Debt consolidation,title_DebtC,title_Green loan,title_Home buying,title_Home improvement,title_Learning and training,title_Major purchase,title_Medical expenses,title_Moving and relocation,title_New Baby and New House (CC Consolidate),title_Other,title_Pay off Lowes Card,title_Paying off higher interest cards & auto,title_Prescription Drug and Medical Costs,title_SAVE,title_Simple Loan Until Contract Is Completed,title_Student Loan,title_Trying to come back to reality!,title_Vacation,title_considerate,title_new day,title_new kitchen for momma!,title_odymeds,initial_list_status_f,initial_list_status_w,last_pymnt_d_Apr-2015,last_pymnt_d_Apr-2016,last_pymnt_d_Aug-2015,last_pymnt_d_Aug-2016,last_pymnt_d_Dec-2015,last_pymnt_d_Dec-2016,last_pymnt_d_Feb-2015,last_pymnt_d_Feb-2016,last_pymnt_d_Jan-2015,last_pymnt_d_Jan-2016,last_pymnt_d_Jan-2017,last_pymnt_d_Jul-2015,last_pymnt_d_Jul-2016,last_pymnt_d_Jun-2015,last_pymnt_d_Jun-2016,last_pymnt_d_Mar-2015,last_pymnt_d_Mar-2016,last_pymnt_d_May-2015,last_pymnt_d_May-2016,last_pymnt_d_Nov-2015,last_pymnt_d_Nov-2016,last_pymnt_d_Oct-2015,last_pymnt_d_Oct-2016,last_pymnt_d_Sep-2015,last_pymnt_d_Sep-2016,next_pymnt_d_Feb-2017,next_pymnt_d_Jan-2017,next_pymnt_d_Jul-2016,next_pymnt_d_Mar-2017,last_credit_pull_d_Apr-2015,last_credit_pull_d_Apr-2016,last_credit_pull_d_Aug-2015,last_credit_pull_d_Aug-2016,last_credit_pull_d_Dec-2014,last_credit_pull_d_Dec-2015,last_credit_pull_d_Dec-2016,last_credit_pull_d_Feb-2015,last_credit_pull_d_Feb-2016,last_credit_pull_d_Jan-2015,last_credit_pull_d_Jan-2016,last_credit_pull_d_Jan-2017,last_credit_pull_d_Jul-2015,last_credit_pull_d_Jul-2016,last_credit_pull_d_Jun-2015,last_credit_pull_d_Jun-2016,last_credit_pull_d_Mar-2015,last_credit_pull_d_Mar-2016,last_credit_pull_d_May-2015,last_credit_pull_d_May-2016,last_credit_pull_d_Nov-2015,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,0.0,11.0,2.0,19108.0,19.0,13668.88,13668.88,4519.68,4519.68,2331.12,2188.56,0.0,0.0,0.0,379.39,0.0,1.0,0.0,0.0,31329.0,284700.0,6.0,2848.0,0.0,0.0,294.0,11.0,6.0,2.0,2.0,6.0,9.0,6.0,8.0,6.0,9.0,9.0,11.0,0.0,0.0,2.0,78.9,0.0,2.0,298100.0,31329.0,281300.0,13400.0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,0.0,7.0,0.0,7722.0,9.0,6635.69,6635.69,3572.97,3572.97,2964.31,608.66,0.0,0.0,0.0,298.58,0.0,1.0,0.0,0.0,55387.0,13000.0,2.0,7912.0,0.0,0.0,91.0,9.0,9.0,0.0,0.0,3.0,3.0,3.0,3.0,5.0,4.0,3.0,7.0,0.0,0.0,2.0,100.0,0.0,0.0,88635.0,55387.0,12500.0,75635.0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,1.0,9.0,0.0,20862.0,19.0,0.00,0.00,26224.23,26224.23,25000.00,1224.23,0.0,0.0,0.0,20807.39,0.0,1.0,0.0,0.0,305781.0,38400.0,2.0,33976.0,0.0,0.0,168.0,13.0,13.0,3.0,0.0,3.0,3.0,5.0,6.0,7.0,5.0,3.0,9.0,0.0,0.0,0.0,100.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,0.0,16.0,0.0,51507.0,24.0,19263.77,19263.77,10271.36,10271.36,8736.23,1535.13,0.0,0.0,0.0,858.05,0.0,1.0,0.0,0.0,221110.0,79900.0,1.0,13819.0,0.0,0.0,379.0,19.0,19.0,2.0,0.0,7.0,9.0,9.0,11.0,4.0,13.0,9.0,16.0,0.0,0.0,0.0,91.7,0.0,0.0,304003.0,74920.0,41500.0,42503.0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,4.0,18.0,1.0,9568.0,19.0,0.00,0.00,9190.49,9190.49,8650.00,540.49,0.0,0.0,0.0,8251.42,0.0,1.0,0.0,0.0,18926.0,20750.0,17.0,1051.0,0.0,0.0,95.0,0.0,0.0,0.0,0.0,2.0,17.0,2.0,2.0,2.0,17.0,13.0,18.0,0.0,0.0,12.0,100.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [149]:
model = sm.OLS(y_e, X).fit()

In [150]:
pDF = pd.DataFrame(data=model.pvalues)

In [151]:
pDF.reset_index(inplace = True)
pd.options.display.float_format = '{:.4f}'.format
pDF.rename({"index":"feature",0:"p_val"}, axis="columns", inplace=True)

In [152]:
pDF.columns

Index(['feature', 'p_val'], dtype='object')

In [161]:
pDF = pDF[pDF.p_val < .000000000001]
final_f = pDF.feature.tolist()
X_final = X[final_f]
#X_final = X_final.drop(columns=['id'])
pDF.describe()

        p_val
count 35.0000
mean   0.0000
std    0.0000
min    0.0000
25%    0.0000
50%    0.0000
75%    0.0000
max    0.0000

In [162]:
rfc_2 = ensemble.RandomForestClassifier()

cross_val_score(rfc_2, X_final, Y, cv=10)

array([0.94830329, 0.92507896, 0.95433497, 0.96245637, 0.94998813,
       0.9431489 , 0.92222565, 0.96010354, 0.9466122 , 0.96017195])

In [ ]:
#77 vars
#array([0.97485218, 0.97216879, 0.97660944, 0.97896037, 0.95661363,
       #0.96523391, 0.96072099, 0.97903061, 0.97665471, 0.97803163])